project_id = "dryngkjeerlssebnpymb"

[functions.cnpjlookup]
verify_jwt = false

[functions.backup-restore]
verify_jwt = false

[functions.cep-lookup]
verify_jwt = false

[functions.delete-user]
verify_jwt = false

[functions.notify-occurrence]
verify_jwt = false

[functions.matrix-ai-fill]
verify_jwt = false

[functions.process-email-queue]
verify_jwt = true

[functions.send-transactional-email]
verify_jwt = false

[functions.preview-transactional-email]
verify_jwt = false

[functions.handle-email-unsubscribe]
verify_jwt = false

[functions.handle-email-suppression]
verify_jwt = false

[functions.installer-send-message]
verify_jwt = false

[functions.installer-read-messages]
verify_jwt = false

[functions.duplicate-kit]
verify_jwt = false

[functions.validate-store-token]
verify_jwt = false

[functions.ai-field-mapping]
verify_jwt = false
